wechat:
  token: "my_token"
  appId: "wx154dff7157e77bbe"
  appSecret: "dd53602b4a70543e657353ac54322c1a"
  testAppId: "wx154dff7157e77bbe"
  testAppSecret: "dd53602b4a70543e657353ac54322c1a"
  apis:
    access_token:
      access_token_get_url: "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s"
    menu:
      menu_create_url: "https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s"
      menu_query_url: "https://api.weixin.qq.com/cgi-bin/get_current_selfmenu_info?access_token=%s"
      menu_delete_url: "https://api.weixin.qq.com/cgi-bin/menu/delete?access_token=%s"
      conditional_menu_create_url: "https://api.weixin.qq.com/cgi-bin/menu/addconditional?access_token=%s"
      conditional_menu_delete_url: "https://api.weixin.qq.com/cgi-bin/menu/delconditional?access_token=%s"
      conditional_menu_try_match_url: "https://api.weixin.qq.com/cgi-bin/menu/trymatch?access_token=%s"
      conditional_menu_query_url: "https://api.weixin.qq.com/cgi-bin/menu/get?access_token=%s"
    user:
      user_tag_create_url: "https://api.weixin.qq.com/cgi-bin/tags/create?access_token=%s"
      user_tag_get_url: "https://api.weixin.qq.com/cgi-bin/tags/get?access_token=%s"
      user_tag_update_url: "https://api.weixin.qq.com/cgi-bin/tags/update?access_token=%s"
      user_tag_delete_url: "https://api.weixin.qq.com/cgi-bin/tags/delete?access_token=%s"
      user_tag_get_subscribers_url: "https://api.weixin.qq.com/cgi-bin/user/tag/get?access_token=%s"
      user_tag_batch_tagging_url: "https://api.weixin.qq.com/cgi-bin/tags/members/batchtagging?access_token=%s"
      user_tag_batch_untagging_url: "https://api.weixin.qq.com/cgi-bin/tags/members/batchuntagging?access_token=%s"
      user_tag_get_user_tag_url: "https://api.weixin.qq.com/cgi-bin/tags/getidlist?access_token=%s"
      user_remark_update_url: "https://api.weixin.qq.com/cgi-bin/user/info/updateremark?access_token=%s"
      user_info_get_url: "https://api.weixin.qq.com/cgi-bin/user/info?access_token=%s&openid=%s&lang=zh_CN"
      user_info_batch_get_url: "https://api.weixin.qq.com/cgi-bin/user/info/batchget?access_token=%s"
      user_list_get_url: "https://api.weixin.qq.com/cgi-bin/user/get?access_token=%s&next_openid=%s"
      user_blocklist_get_url: "https://api.weixin.qq.com/cgi-bin/tags/members/getblacklist?access_token=%s"
      user_blocklist_batch_block_url: "https://api.weixin.qq.com/cgi-bin/tags/members/batchblacklist?access_token=%s"
    message:
      message_send_by_user_tag_url: "https://api.weixin.qq.com/cgi-bin/message/mass/sendall?access_token=%s"
      message_send_by_openids_url: "https://api.weixin.qq.com/cgi-bin/message/mass/send?access_token=%s"
      message_delete_url: "https://api.weixin.qq.com/cgi-bin/message/mass/delete?access_token=%s"
      message_preview_url: "POST https://api.weixin.qq.com/cgi-bin/message/mass/preview?access_token=%s"
      message_send_result_url: "https://api.weixin.qq.com/cgi-bin/message/mass/get?access_token=%s"
      message_send_speed_get_url: "https://api.weixin.qq.com/cgi-bin/message/mass/speed/get?access_token=%s"
      message_send_speed_set_url: "https://api.weixin.qq.com/cgi-bin/message/mass/speed/set?access_token=%s"
      template_industry_set_url: "https://api.weixin.qq.com/cgi-bin/template/api_set_industry?access_token=%s"
      template_industry_get_url: "https://api.weixin.qq.com/cgi-bin/template/get_industry?access_token=%s"
      template_id_get_url: "https://api.weixin.qq.com/cgi-bin/template/api_add_template?access_token=%s"
      template_id_list_get_url: "https://api.weixin.qq.com/cgi-bin/template/get_all_private_template?access_token=%s"
      template_remove_url: "https://api.weixin.qq.com/cgi-bin/template/del_private_template?access_token=%s"
      template_send_url: "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=%s"
server:
  port: 80