app:
  domain: "http://jtg.mynatapp.cc"
wechat:
  token: "my_token"
  appId: "wx154dff7157e77bbe"
  appSecret: "dd53602b4a70543e657353ac54322c1a"
  testAppId: "wx154dff7157e77bbe"
  testAppSecret: "dd53602b4a70543e657353ac54322c1a"
  jobs:
    # time unit: ms
    refreshAccessToken:
      enable: false
      fixedRate: 6400000
      initialDelay: 3000
    refreshJsapiTicket:
      enable: false
      fixedRate: 6400000
      initialDelay: 3000
    refreshJssdkAccessToken:
      enable: false
      fixedRate: 6400000
      initialDelay: 3000
  project_settings:
    domain: "master"
    environment: "test"
  domains:
    master: "https://api.weixin.qq.com"
    backup: "https://api2.weixin.qq.com"
    shanghai: "https://sh.api.weixin.qq.com"
    shenzhen: "https://sz.api.weixin.qq.com"
  apis:
    access_token:
      access_token_get_uri: "/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s"
    menu:
      menu_create_uri: "/cgi-bin/menu/create?access_token=%s"
      menu_query_uri: "/cgi-bin/get_current_selfmenu_info?access_token=%s"
      menu_delete_uri: "/cgi-bin/menu/delete?access_token=%s"
      conditional_menu_create_uri: "/cgi-bin/menu/addconditional?access_token=%s"
      conditional_menu_delete_uri: "/cgi-bin/menu/delconditional?access_token=%s"
      conditional_menu_try_match_uri: "/cgi-bin/menu/trymatch?access_token=%s"
      conditional_menu_query_uri: "/cgi-bin/menu/get?access_token=%s"
    user:
      user_tag_create_uri: "/cgi-bin/tags/create?access_token=%s"
      user_tag_get_uri: "/cgi-bin/tags/get?access_token=%s"
      user_tag_update_uri: "/cgi-bin/tags/update?access_token=%s"
      user_tag_delete_uri: "/cgi-bin/tags/delete?access_token=%s"
      user_tag_get_subscribers_uri: "/cgi-bin/user/tag/get?access_token=%s"
      user_tag_batch_tagging_uri: "/cgi-bin/tags/members/batchtagging?access_token=%s"
      user_tag_batch_untagging_uri: "/cgi-bin/tags/members/batchuntagging?access_token=%s"
      user_tag_get_user_tag_uri: "/cgi-bin/tags/getidlist?access_token=%s"
      user_remark_update_uri: "/cgi-bin/user/info/updateremark?access_token=%s"
      user_info_get_uri: "/cgi-bin/user/info?access_token=%s&openid=%s&lang=zh_CN"
      user_info_batch_get_uri: "/cgi-bin/user/info/batchget?access_token=%s"
      user_list_get_uri: "/cgi-bin/user/get?access_token=%s&next_openid=%s"
      user_blocklist_get_uri: "/cgi-bin/tags/members/getblacklist?access_token=%s"
      user_blocklist_batch_block_uri: "/cgi-bin/tags/members/batchblacklist?access_token=%s"
    message:
      message_send_by_user_tag_uri: "/cgi-bin/message/mass/sendall?access_token=%s"
      message_send_by_openids_uri: "/cgi-bin/message/mass/send?access_token=%s"
      message_delete_uri: "/cgi-bin/message/mass/delete?access_token=%s"
      message_preview_uri: "/cgi-bin/message/mass/preview?access_token=%s"
      message_send_result_uri: "/cgi-bin/message/mass/get?access_token=%s"
      message_send_speed_get_uri: "/cgi-bin/message/mass/speed/get?access_token=%s"
      message_send_speed_set_uri: "/cgi-bin/message/mass/speed/set?access_token=%s"
      template_industry_set_uri: "/cgi-bin/template/api_set_industry?access_token=%s"
      template_industry_get_uri: "/cgi-bin/template/get_industry?access_token=%s"
      template_id_get_uri: "/cgi-bin/template/api_add_template?access_token=%s"
      template_id_list_get_uri: "/cgi-bin/template/get_all_private_template?access_token=%s"
      template_remove_uri: "/cgi-bin/template/del_private_template?access_token=%s"
      template_send_uri: "/cgi-bin/message/template/send?access_token=%s"
    jsapi:
      jsapi_ticket_get_uri: "/cgi-bin/ticket/getticket?type=jsapi&access_token=%s"
      weixin_user_oauth_get_code_url: "https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=%s#wechat_redirect"
      weixin_user_oauth_get_access_token_uri: "/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code"
      weixin_user_oauth_refresh_access_token_uri: "/sns/oauth2/refresh_token?appid=%s&grant_type=refresh_token&refresh_token=%s"
      weixin_user_oauth_get_user_info_uri: "/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN"
      weixin_user_oauth_verify_access_token_validity_uri: "/sns/auth?access_token=%s&openid=%s"
server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp