spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-curd?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /springbootcrud
  port: 80
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.taogen.demo.springbootcrud.module.*.entity