# logging
logging:
  config: classpath:log4j2.xml

# data access
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-curd?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  # web
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.taogen.demo.springbootcrud.module.*.entity

# web mvc
server:
  servlet:
    context-path: "/springbootcrud"
  port: 80
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method